# Define compiler
CXX = g++

# Define flags
CXXFLAGS =

# Define the target executable
TARGET = day1

all: $(TARGET)

$(TARGET): day1.cpp
	$(CXX) $(CXXFLAGS) -o $(TARGET) day1.cpp

clean:
	$(RM) $(TARGET)
